#!/bin/bash

set -e

echo "== Install badvpn by julak vpn =="
apt update -y
apt install -y wget cmake make gcc screen

echo "== Download badvpn source =="
cd /usr/local/src
rm -rf badvpn
wget https://github.com/ambrop72/badvpn/archive/refs/heads/master.zip -O badvpn.zip
unzip badvpn.zip
cd badvpn-master

echo "== Build badvpn-udpgw =="
cmake -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1
make

echo "== Install binary =="
cp udpgw/badvpn-udpgw /usr/sbin/badvpn-udpgw
chmod +x /usr/sbin/badvpn-udpgw

echo "== Done =="
echo "badvpn installed"
